### ISSUE TITLE
Map not loading on a flutter web app which loaded from a secure (HTTPS) connection due Mixed Content blocking in Chrome

### ISSUE THREAD

**Issue by MaazAdrees81** [Bestfastfire/map_picker_flutter#1]
The web app does not show map when the method `MapPickerTemplate.dialogAddressPicker(context: context)` is called, but instead show circular progress indicators. When checking the web the console, The request for map images were blocked due to mixed content because the website was loaded from a secure **_(HTTPS)_** connection and the call made for map images was through unsecure **_(HTTP)_** connection. Upon checking the plugins files I came across this url                       `'http://mt1.google.com/vt/lyrs=m@129&x=$x&y=$y&z=$z';`, 
in the 
> map_picker.dart

 This url is actually causing the issue. And it is a simple fix, the above mentioned url just have to be converted to a secure link exactly like this one `'https://mt1.google.com/vt/lyrs=m@129&x=$x&y=$y&z=$z';`

Please try to fix and update the plugin as soon as possible. Thank you

**Comment by Bestfastfire** [comment]
Thanks for the suggestion, I made the correction and uploaded version
