### ISSUE TITLE
Cannot get MPAddress on mobiles if use MaterialPush

### ISSUE THREAD

**Issue by hymrdjnh1999** [Bestfastfire/map_picker_flutter#2]

**Comment by Bestfastfire** [comment]
Can you provide example?

**Comment by hymrdjnh1999** [comment]
On mobile device after i use materialRoutePage address i retrieve is nulll

**Comment by Bestfastfire** [comment]
> On mobile device after i use materialRoutePage address i retrieve is nulll

Please, add on issue code example and if you passing the google key in constructor
